version: '3.0'

services:
  deno:
    container_name: gpt-processor
    image: denoland/deno:1.34.3
    command: run --allow-env --allow-net --allow-read --watch --unstable main.ts
    volumes: 
      - ./src:/app
    working_dir: /app
    ports:
      - "1993:1993"